class Job {
  final String jobId;
  final String jobTitle;
  final String companyName;
  final String location;
  final String jobType;
  final String salary;
  final String experienceRequired;
  final List<String> skills;
  final String jobDescription;
  final String postedDate;
  final String applyLink;
  final String source;
  final bool remoteFriendly;
  final String? companyLogoUrl;
  final String? industry;
  final String? educationRequired;

  const Job({
    required this.jobId,
    required this.jobTitle,
    required this.companyName,
    required this.location,
    required this.jobType,
    required this.salary,
    required this.experienceRequired,
    required this.skills,
    required this.jobDescription,
    required this.postedDate,
    required this.applyLink,
    required this.source,
    required this.remoteFriendly,
    this.companyLogoUrl,
    this.industry,
    this.educationRequired,
  });
}

final List<Job> availableJobs = [
  Job(
    jobId: "001",
    jobTitle: "Flutter Developer",
    companyName: "TechCorp Solutions",
    location: "Bangalore",
    jobType: "Full-time",
    salary: "₹12L - ₹18L",
    experienceRequired: "2-4 years",
    skills: ["Flutter", "Dart", "Firebase", "REST APIs", "Git"],
    jobDescription:
        "Build beautiful mobile apps with Flutter. Work on cross-platform development and integrate with backend services.",
    postedDate: "2 days ago",
    applyLink: "https://techcorp.com/careers/flutter-dev-001",
    source: "LinkedIn",
    remoteFriendly: false,
    companyLogoUrl: "https://example.com/techcorp-logo.png",
    industry: "Tech",
    educationRequired: "Bachelor's in Computer Science or related field",
  ),
  Job(
    jobId: "002",
    jobTitle: "UI/UX Designer",
    companyName: "DesignPro Studio",
    location: "Remote",
    jobType: "Full-time",
    salary: "₹8L - ₹14L",
    experienceRequired: "1-3 years",
    skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
    jobDescription:
        "Design intuitive user interfaces for web and mobile applications. Collaborate with development teams.",
    postedDate: "1 day ago",
    applyLink: "https://designpro.com/jobs/ux-designer-002",
    source: "Indeed",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/designpro-logo.png",
    industry: "Design",
    educationRequired: "Bachelor's in Design or related field",
  ),
  Job(
    jobId: "003",
    jobTitle: "Backend Engineer",
    companyName: "CloudBase Technologies",
    location: "Hyderabad",
    jobType: "Full-time",
    salary: "₹15L - ₹22L",
    experienceRequired: "3-5 years",
    skills: ["Node.js", "Python", "AWS", "MongoDB", "Docker", "Kubernetes"],
    jobDescription:
        "Work on scalable backend systems using modern technologies. Design and implement microservices architecture.",
    postedDate: "3 days ago",
    applyLink: "https://cloudbase.com/careers/backend-eng-003",
    source: "Company Website",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/cloudbase-logo.png",
    industry: "Tech",
    educationRequired: "Bachelor's in Computer Science",
  ),
  Job(
    jobId: "004",
    jobTitle: "Frontend Developer Intern",
    companyName: "StartupXYZ",
    location: "Mumbai",
    jobType: "Internship",
    salary: "₹15,000 - ₹25,000",
    experienceRequired: "0-1 years",
    skills: ["React.js", "JavaScript", "HTML", "CSS", "Git"],
    jobDescription:
        "Learn and contribute to frontend development projects. Work with senior developers on user-facing features.",
    postedDate: "5 days ago",
    applyLink: "https://startupxyz.com/internships/frontend-004",
    source: "AngelList",
    remoteFriendly: false,
    companyLogoUrl: "https://example.com/startupxyz-logo.png",
    industry: "Tech",
    educationRequired: "Currently pursuing Computer Science degree",
  ),
  Job(
    jobId: "005",
    jobTitle: "Data Scientist",
    companyName: "DataViz Analytics",
    location: "Remote",
    jobType: "Full-time",
    salary: "₹18L - ₹28L",
    experienceRequired: "2-4 years",
    skills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "SQL",
      "Pandas",
      "NumPy",
    ],
    jobDescription:
        "Analyze complex datasets and build machine learning models. Present insights to stakeholders.",
    postedDate: "1 week ago",
    applyLink: "https://dataviz.com/jobs/data-scientist-005",
    source: "Naukri",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/dataviz-logo.png",
    industry: "Analytics",
    educationRequired: "Master's in Data Science or Statistics",
  ),
  Job(
    jobId: "006",
    jobTitle: "DevOps Engineer",
    companyName: "InfraTech Solutions",
    location: "Pune",
    jobType: "Full-time",
    salary: "₹14L - ₹20L",
    experienceRequired: "2-5 years",
    skills: ["AWS", "Docker", "Jenkins", "Terraform", "Kubernetes", "Linux"],
    jobDescription:
        "Manage cloud infrastructure and automate deployment processes. Ensure system reliability and scalability.",
    postedDate: "4 days ago",
    applyLink: "https://infratech.com/careers/devops-006",
    source: "LinkedIn",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/infratech-logo.png",
    industry: "Tech",
    educationRequired: "Bachelor's in Engineering",
  ),
  Job(
    jobId: "007",
    jobTitle: "Product Manager",
    companyName: "InnovateCorp",
    location: "Delhi",
    jobType: "Full-time",
    salary: "₹20L - ₹30L",
    experienceRequired: "3-6 years",
    skills: [
      "Product Strategy",
      "Agile",
      "User Research",
      "Analytics",
      "Roadmapping",
    ],
    jobDescription:
        "Drive product vision and strategy. Work with cross-functional teams to deliver user-centric products.",
    postedDate: "2 days ago",
    applyLink: "https://innovatecorp.com/jobs/pm-007",
    source: "Company Website",
    remoteFriendly: false,
    companyLogoUrl: "https://example.com/innovatecorp-logo.png",
    industry: "Tech",
    educationRequired: "MBA or Bachelor's with relevant experience",
  ),
  Job(
    jobId: "008",
    jobTitle: "Freelance Graphic Designer",
    companyName: "CreativeHub",
    location: "Remote",
    jobType: "Freelance",
    salary: "₹500 - ₹2,000 per project",
    experienceRequired: "1-3 years",
    skills: ["Photoshop", "Illustrator", "InDesign", "Branding", "Logo Design"],
    jobDescription:
        "Create visual designs for various clients. Work on branding, marketing materials, and digital assets.",
    postedDate: "1 day ago",
    applyLink: "https://creativehub.com/freelance/graphic-008",
    source: "Upwork",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/creativehub-logo.png",
    industry: "Design",
    educationRequired: "Portfolio required",
  ),
  Job(
    jobId: "009",
    jobTitle: "Android Developer",
    companyName: "MobileFirst Tech",
    location: "Chennai",
    jobType: "Full-time",
    salary: "₹10L - ₹16L",
    experienceRequired: "1-3 years",
    skills: ["Kotlin", "Java", "Android SDK", "Retrofit", "Room Database"],
    jobDescription:
        "Develop native Android applications. Work on performance optimization and user experience enhancement.",
    postedDate: "6 days ago",
    applyLink: "https://mobilefirst.com/careers/android-009",
    source: "Indeed",
    remoteFriendly: false,
    companyLogoUrl: "https://example.com/mobilefirst-logo.png",
    industry: "Tech",
    educationRequired: "Bachelor's in Computer Science",
  ),
  Job(
    jobId: "010",
    jobTitle: "Quality Assurance Tester",
    companyName: "TestPro Solutions",
    location: "Remote",
    jobType: "Part-time",
    salary: "₹6L - ₹10L",
    experienceRequired: "0-2 years",
    skills: [
      "Manual Testing",
      "Selenium",
      "Test Cases",
      "Bug Reporting",
      "API Testing",
    ],
    jobDescription:
        "Ensure software quality through comprehensive testing. Write test cases and report bugs.",
    postedDate: "3 days ago",
    applyLink: "https://testpro.com/jobs/qa-010",
    source: "Glassdoor",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/testpro-logo.png",
    industry: "Tech",
    educationRequired: "Any graduate with interest in testing",
  ),
  Job(
    jobId: "011",
    jobTitle: "Machine Learning Engineer",
    companyName: "AI Innovations",
    location: "Bangalore",
    jobType: "Full-time",
    salary: "₹22L - ₹35L",
    experienceRequired: "3-5 years",
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "MLOps",
      "Deep Learning",
      "Computer Vision",
    ],
    jobDescription:
        "Build and deploy machine learning models at scale. Work on cutting-edge AI projects.",
    postedDate: "1 day ago",
    applyLink: "https://aiinnovations.com/careers/ml-eng-011",
    source: "LinkedIn",
    remoteFriendly: true,
    companyLogoUrl: "https://example.com/aiinnovations-logo.png",
    industry: "AI/ML",
    educationRequired: "Master's in Computer Science or AI",
  ),
  Job(
    jobId: "012",
    jobTitle: "Business Analyst",
    companyName: "FinanceFlow Corp",
    location: "Mumbai",
    jobType: "Full-time",
    salary: "₹12L - ₹18L",
    experienceRequired: "2-4 years",
    skills: [
      "SQL",
      "Excel",
      "Tableau",
      "Business Intelligence",
      "Requirements Analysis",
    ],
    jobDescription:
        "Analyze business processes and recommend improvements. Work with stakeholders to gather requirements.",
    postedDate: "4 days ago",
    applyLink: "https://financeflow.com/jobs/ba-012",
    source: "Naukri",
    remoteFriendly: false,
    companyLogoUrl: "https://example.com/financeflow-logo.png",
    industry: "Finance",
    educationRequired: "Bachelor's in Business or related field",
  ),
];
